language: c
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq valgrind
script:
    - ./waf distclean configure build --valgrind
    - ./waf distclean configure --optimize build --valgrind
